SET IDENTITY_INSERT [dbo].[questions] ON;
INSERT INTO [dbo].[questions] ([id], [questionText], [answer1], [answer2], [answer3], [answer4], [correctAnswer], [categoryId]) VALUES
-- Minecraft questions
(1, N'Which material do you need to make a Nether portal?', N'Obsidian', N'Diamond', N'Cobblestone', N'Wood', 1, 1),
(2, N'What is the main enemy in the Nether?', N'Zombie', N'Ghast', N'Skeleton', N'Spider', 2, 1),
(3, N'Which tool is used to mine stone faster?', N'Axe', N'Pickaxe', N'Shovel', N'Sword', 2, 1),
(4, N'What do Creepers drop when killed?', N'TNT', N'Gunpowder', N'Diamonds', N'Bones', 2, 1),
(5, N'Which animal can you milk in Minecraft?', N'Cow', N'Sheep', N'Pig', N'Chicken', 1, 1),
(6, N'Which block can you use to make enchanting tables?', N'Obsidian', N'Diamond', N'Iron', N'Gold', 1, 1),
(7, N'What do you need to tame a wolf?', N'Bones', N'Fish', N'Meat', N'Apple', 1, 1),
(8, N'Which dimension contains the Ender Dragon?', N'Overworld', N'Nether', N'The End', N'None', 3, 1),
(9, N'Which item is needed to respawn the Ender Dragon?', N'Ender Pearl', N'Eye of Ender', N'Dragon Egg', N'Bedrock', 2, 1),
(10, N'Which mob explodes when close to the player?', N'Zombie', N'Creeper', N'Skeleton', N'Slime', 2, 1),
(11, N'What is the primary function of a furnace?', N'Brewing', N'Cooking', N'Smelting', N'Crafting', 3, 1),
(12, N'Which block is immune to explosions?', N'Wood', N'Obsidian', N'Dirt', N'Sand', 2, 1),
(13, N'Which mob drops Ender Pearls?', N'Skeleton', N'Zombie', N'Enderman', N'Spider', 3, 1),
(14, N'Which potion effect does a golden apple give?', N'Regeneration', N'Speed', N'Invisibility', N'Fire Resistance', 1, 1),
(15, N'Which block do you need to grow Nether Wart?', N'Soul Sand', N'Dirt', N'Grass', N'Sand', 1, 1),
(16, N'Which biome is known for having lots of mushrooms?', N'Forest', N'Mushroom Island', N'Desert', N'Plains', 2, 1),
(17, N'Which tool is required to mine diamonds?', N'Axe', N'Pickaxe', N'Shovel', N'Sword', 2, 1),
(18, N'Which mob shoots fireballs?', N'Ghast', N'Zombie', N'Skeleton', N'Creeper', 1, 1),
(19, N'Which item is used to craft TNT?', N'Gunpowder', N'Iron', N'Coal', N'Sand', 1, 1),
(20, N'Which food restores the most hunger?', N'Bread', N'Steak', N'Apple', N'Carrot', 2, 1),

-- Rocket League questions
(21, N'What is the maximum number of players on a standard Rocket League team?', N'3', N'4', N'5', N'6', 1, 2),
(22, N'Which platform did Rocket League originally release on?', N'PC', N'Xbox One', N'PS4', N'Nintendo Switch', 3, 2),
(23, N'What is the default car in Rocket League called?', N'Octane', N'Dominus', N'Breakout', N'Merc', 1, 2),
(24, N'What resource do players use to boost?', N'Fuel', N'Boost Pads', N'Energy', N'Coins', 2, 2),
(25, N'What happens when a player performs an "Aerial"?', N'Drives on the wall', N'Jumps and hits the ball mid-air', N'Boosts faster', N'Flips backwards', 2, 2),
(26, N'Which Rocket League rank is higher?', N'Gold I', N'Platinum I', N'Silver III', N'Diamond II', 4, 2),
(27, N'Which mode is played with 1v1?', N'Singles', N'Doubles', N'Standard', N'Chaos', 1, 2),
(28, N'What item grants an instant goal in Rumble mode?', N'Boot', N'Freezer', N'Plunger', N'Ball', 3, 2),
(29, N'Which of these is a popular aerial technique?', N'Double Tap', N'Drag Shot', N'Ceiling Shot', N'All of the above', 4, 2),
(30, N'What is the official competitive platform for Rocket League tournaments?', N'RLCS', N'RLRS', N'RLCP', N'RLCU', 1, 2),
(31, N'What does "flip reset" mean?', N'Resetting boost after a flip', N'Hitting the ball with all wheels in air', N'Flipping backwards', N'Scoring a goal after a flip', 2, 2),
(32, N'Which car hitbox is considered the most versatile?', N'Octane', N'Dominus', N'Breakout', N'Fennec', 1, 2),
(33, N'How many boost pads are on a standard map?', N'12', N'18', N'24', N'36', 4, 2),
(34, N'Which mode uses a giant ball that deals more knockback?', N'Rumble', N'Dropshot', N'Snow Day', N'Soccar', 4, 2),
(35, N'Which of these is a Rumble power-up?', N'Grappling Hook', N'Magnet', N'Teleport', N'Shield', 3, 2),
(36, N'What is the fastest speed a car can reach without boost?', N'1200 UU/h', N'1400 UU/h', N'1600 UU/h', N'1800 UU/h', 3, 2),
(37, N'Which skill is most important for air control?', N'Dribbling', N'Aerials', N'Half-flips', N'Flicks', 2, 2),
(38, N'What does "demo" mean in Rocket League?', N'Scoring a goal', N'Destroying the ball', N'Taking out an opponent by hitting them', N'Boost stealing', 3, 2),
(39, N'Which of these is a common kickoff strategy?', N'Drag kickoff', N'Diagonal kickoff', N'Fake kickoff', N'All of the above', 4, 2),
(40, N'What does "GC" stand for in Rocket League?', N'Grand Champion', N'Great Control', N'Game Champion', N'Golden Car', 1, 2);
SET IDENTITY_INSERT [dbo].[questions] OFF;